### ISSUE TITLE
initialize connection failure mismatch of args

### ISSUE THREAD

**Issue by gmcb** [emcvipr/controller-openstack-cinder#16]
2016-06-21 14:00:22.351 35358 ERROR cinder.volume.manager [req-0696d339-7d14-439c-9783-12db4cb7b99f 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 be905aea83134411ba7ce9cfae6a8328 - - -] Driver initialize connection failed (error: Bad or unexpected response from the storage volume backend API:
General Exception: <type 'exceptions.TypeError'>
Stack Trace:
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 136, in try_and_retry
 return func(_args, *_kwargs)
File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 1084, in initialize_connection
 autodiscovery=True)
TypeError: create() takes exactly 17 arguments (14 given)
).

copperhead
Software Versions
vipr-3.5.0.0.78703be     Current Version
# git show

commit 02a8c3454a9556f0d43e30a054f80139028eade4
Merge: 3e7696b a94b937
Author: raviedpuganti raviedpuganti@users.noreply.github.com
Date:   Wed Jun 15 17:04:55 2016 +0530

```
Merge pull request #15 from emcvipr/feature-yoda-release

yoda release related changes
```

**Comment by gmcb** [comment]
I get this error for NPIV deploy where the WWPNs are from virtual adapters. 

2016-07-06 11:58:20.717 9011 INFO powervc_cinder.zonemanager.powervc_utils [req-a8cd81e0-e17c-496a-b569-7ee727012714 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 be905aea83134411ba7ce9cfae6a8328 - - -] AddFCZone initialize_connection Failure Volume <cinder.db.sqlalchemy.models.Volume object at 0x71757d0> Connector {u'connection_type': u'npiv', u'wwpns': [u'C05076082613001A', u'C05076082613001B'], u'wwnns': [u'C05076082613001A', u'C05076082613001B'], u'is_npiv_migration': False, u'host': u'FAKE-npiv2-1a12e6c0-00000019', u'phy_to_virt_initiators': {u'21000024ff7a0871': [u'C05076082613001A', u'C05076082613001B']}, u'os_type': u'rhel'}
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils [req-a8cd81e0-e17c-496a-b569-7ee727012714 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 be905aea83134411ba7ce9cfae6a8328 - - -] Bad or unexpected response from the storage volume backend API:
General Exception: <type 'exceptions.TypeError'>
Stack Trace:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 136, in try_and_retry
    return func(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 1084, in initialize_connection
    autodiscovery=True)
TypeError: create() takes exactly 17 arguments (14 given)
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils Traceback (most recent call last):
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils   File "/usr/lib/python2.7/site-packages/powervc_cinder/zonemanager/powervc_utils.py", line 88, in decorator
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils     info = initialize_connection(self, _args, *_kwargs)
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/fc.py", line 177, in initialize_connection
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils     hostname)
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 154, in try_and_retry
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils     data=exception_message)
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API:
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils General Exception: <type 'exceptions.TypeError'>
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils Stack Trace:
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils Traceback (most recent call last):
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 136, in try_and_retry
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils     return func(_args, *_kwargs)
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 1084, in initialize_connection
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils     autodiscovery=True)
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils TypeError: create() takes exactly 17 arguments (14 given)
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils
2016-07-06 11:58:20.717 9011 ERROR powervc_cinder.zonemanager.powervc_utils
2016-07-06 11:58:20.718 9011 ERROR cinder.volume.manager [req-a8cd81e0-e17c-496a-b569-7ee727012714 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 be905aea83134411ba7ce9cfae6a8328 - - -] Driver initialize connection failed (error: Bad or unexpected response from the storage volume backend API:
General Exception: <type 'exceptions.TypeError'>
Stack Trace:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 136, in try_and_retry
    return func(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 1084, in initialize_connection
    autodiscovery=True)
TypeError: create() takes exactly 17 arguments (14 given)
).

**Comment by gmcb** [comment]
For VSCSI connected volumes which use the wwpn of the vioss I get a different error. The first initialize_connection is successful and the second initialize_connection for the second VIOS fails: 

2016-07-06 12:00:51.240 9011 INFO powervc_cinder.zonemanager.powervc_utils [req-b0c07af1-9c73-492d-86c2-d028cdae6a9b 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 be905aea83134411ba7ce9cfae6a8328 - - -] AddFCZone initialize_connection Failure Volume <cinder.db.sqlalchemy.models.Volume object at 0x6d09a10> Connector {u'is_npiv_migration': False, u'connection_type': u'pv_vscsi', u'wwpns': [u'21000024ff7a3749', u'21000024ff7a3748'], 'wwnns': [u'21000024ff7a3749', u'21000024ff7a3748'], u'host': u'824742L_2120FDA_3'}
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils [req-b0c07af1-9c73-492d-86c2-d028cdae6a9b 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 be905aea83134411ba7ce9cfae6a8328 - - -] Bad or unexpected response from the storage volume backend API:
ViPR Exception: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)
Stack Trace:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 136, in try_and_retry
    return func(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 1193, in initialize_connection
    e.err_text)
SOSError: u'Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)'
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils Traceback (most recent call last):
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils   File "/usr/lib/python2.7/site-packages/powervc_cinder/zonemanager/powervc_utils.py", line 88, in decorator
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils     info = initialize_connection(self, _args, *_kwargs)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/fc.py", line 177, in initialize_connection
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils     hostname)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 149, in try_and_retry
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils     data=exception_message)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API:
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils ViPR Exception: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils Stack Trace:
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils Traceback (most recent call last):
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 136, in try_and_retry
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils     return func(_args, *_kwargs)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 1193, in initialize_connection
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils     e.err_text)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils SOSError: u'Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)'
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils
2016-07-06 12:00:51.241 9011 ERROR cinder.volume.manager [req-b0c07af1-9c73-492d-86c2-d028cdae6a9b 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 be905aea83134411ba7ce9cfae6a8328 - - -] Driver initialize connection failed (error: Bad or unexpected response from the storage volume backend API:
ViPR Exception: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)
Stack Trace:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 136, in try_and_retry
    return func(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 1193, in initialize_connection
    e.err_text)
SOSError: u'Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)'
).

**Comment by gmcb** [comment]
If a device cannot belong to more than one storage group I believe that will prevent mutli-attach, and VM migration also.
