### ISSUE TITLE
VMAX 3 issue with initialize_connection

### ISSUE THREAD

**Issue by gmcb** [emcvipr/controller-openstack-cinder#18]
or VSCSI connected volumes which use the wwpn of the vioss I get a different error. The first initialize_connection is successful and the second initialize_connection for the second VIOS fails:

2016-07-06 12:00:51.240 9011 INFO powervc_cinder.zonemanager.powervc_utils [req-b0c07af1-9c73-492d-86c2-d028cdae6a9b 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 be905aea83134411ba7ce9cfae6a8328 - - -] AddFCZone initialize_connection Failure Volume Connector {u'is_npiv_migration': False, u'connection_type': u'pv_vscsi', u'wwpns': [u'21000024ff7a3749', u'21000024ff7a3748'], 'wwnns': [u'21000024ff7a3749', u'21000024ff7a3748'], u'host': u'824742L_2120FDA_3'}
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils [req-b0c07af1-9c73-492d-86c2-d028cdae6a9b 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 be905aea83134411ba7ce9cfae6a8328 - - -] Bad or unexpected response from the storage volume backend API:
ViPR Exception: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)
Stack Trace:
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 136, in try_and_retry
return func(args, *kwargs)
File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 1193, in initialize_connection
e.err_text)
SOSError: u'Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)'
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils Traceback (most recent call last):
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils File "/usr/lib/python2.7/site-packages/powervc_cinder/zonemanager/powervc_utils.py", line 88, in decorator
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils info = initialize_connection(self, args, *kwargs)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/fc.py", line 177, in initialize_connection
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils hostname)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 149, in try_and_retry
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils data=exception_message)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API:
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils ViPR Exception: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils Stack Trace:
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils Traceback (most recent call last):
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 136, in try_and_retry
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils return func(args, *kwargs)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 1193, in initialize_connection
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils e.err_text)
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils SOSError: u'Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)'
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils
2016-07-06 12:00:51.240 9011 ERROR powervc_cinder.zonemanager.powervc_utils
2016-07-06 12:00:51.241 9011 ERROR cinder.volume.manager [req-b0c07af1-9c73-492d-86c2-d028cdae6a9b 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 be905aea83134411ba7ce9cfae6a8328 - - -] Driver initialize connection failed (error: Bad or unexpected response from the storage volume backend API:
ViPR Exception: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)
Stack Trace:
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 136, in try_and_retry
return func(args, *kwargs)
File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/vipr/common.py", line 1193, in initialize_connection
e.err_text)
SOSError: u'Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Attach volume (FAKE-vscsi2-e184ab14-00000017-boot-0) to host (824742L_2120FDA_3) initiator (21:00:00:24:FF:7A:37:49) failed: Task: urn:storageos:Task:ff26c1aa-a828-40fb-8e7c-69c8faa0142f:vdc1 is failed with error: Operation failed due to the following error: A general error occurred that is not covered by a more specific error code. (com.emc.cmp.osls.se.symm.impl.MaskHelper.DMGCreate:424 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_FAILED R:10424 file: SymStructBase.cpp line: 127 func: throwOnSymError errcode: 10424 sym err: A device cannot belong to more than one storage group in use by FAST message: MaskHelper::DMGCreate fail)'
).

**Comment by gmcb** [comment]
If a device cannot belong to more than one storage group this will prevent mutli-attach, and vscsi VM migration.
On Power multi-attach is very popular.
